name: Run

on:
  push:
    branches:
      # deploy on updates on main
      - main
  workflow_dispatch:
  repository_dispatch:

jobs:
  build:

    if: github.actor == github.repository_owner
    runs-on: ubuntu-latest

    steps:
    - name: repo-sync
      uses: yehan-coding/yehan-git-sync@v1
      with:
        source_repo_url: git@github.com:${{ github.repository }}.git
        source_branch: main
        destination_repo_url: ${{ secrets.DESTINATION_REPO_URL }}
        destination_branch: main
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
